# Generated by Django 5.1.7 on 2025-03-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_first_name', models.CharField(max_length=100)),
                ('agent_last_name', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254, unique=True)),
                ('agent_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_first_name', models.CharField(max_length=100)),
                ('organizer_last_name', models.CharField(max_length=100)),
                ('organizer_email', models.EmailField(max_length=254, unique=True)),
                ('organizer_phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_first_name', models.CharField(max_length=100)),
                ('artist_last_name', models.CharField(max_length=100)),
                ('primary_genre', models.CharField(blank=True, max_length=100)),
                ('artist_email', models.EmailField(max_length=254, unique=True)),
                ('artist_phone', models.CharField(blank=True, max_length=20)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='api.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_date', models.DateField()),
                ('concert_time', models.TimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='api.artist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizer')),
            ],
        ),
    ]
