# Generated by Django 5.1.7 on 2025-05-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='concert',
            unique_together={('artist', 'concert_date', 'concert_time')},
        ),
    ]
