# Generated by Django 5.1.7 on 2025-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_location_address_alter_concert_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
